# SPDX-FileCopyrightText: 2024 Wolfgang Traylor <wolfgang.traylor@senckenberg.de>
#
# SPDX-License-Identifier: CC0-1.0

# Conda environment file to build documentations for readthedocs.org

name: mmm_readthedocs
channels: conda-forge
dependencies:
  - cmake
  - doxygen
